import { COMMENTS } from '../shared/comments';
import * as ActionTypes from './ActionTypes';

export const Comments= (state=COMMENTS, action) => {
	switch(action.type){
		case ActionTypes.ADD_COMMENT :
			var comment=action.payload;
			comment.id=	state.length; //state contains comments here(see line 4) so length
			//later will be generated by server here we need to hardcode
			comment.date=new Date().toISOString();
			return state.concat(comment); //concat is immutable i.e. creates a new object(that's what we need to do)
			//this added comment is lost when we restart our application
		default: 
			return state;
	}
}